### ISSUE TITLE
Option to show nav buttons / arrows only on non-touch devices

### ISSUE THREAD

**Issue by jchnkl** [andreknieriem/simplelightbox#223]
The current 'nav' option hides the navigation arrows on every device. It would be nice to show them on non-touch devices and hide them on a touch device. I think this would be even a matter of just a media query.

...and as I'm writing this issue:

```css
@media(pointer: coarse) {
  .sl-navigation {
    display: none !important;
  }
}
```
